//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime RentStartDate { get; set; }
        public System.DateTime RentEndDate { get; set; }
        public int CarId { get; set; }
        public int UserId { get; set; }
        public decimal DiscountPrice { get; set; }
        public decimal OrderPrice { get; set; }
        public bool Status { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
